sso-server: http://localhost:8080/sso

server:
  port: 8082
  servlet:
    context-path: /audit

security:
  oauth2:
    client:
      client-id: app_audit
      client-secret: user123
      access-token-uri: ${sso-server}/oauth/token
      user-authorization-uri: ${sso-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${sso-server}/oauth/token_key
