sso-server: http://localhost:8080/sso

server:
  port: 8083
  servlet:
    context-path: /yyc
security:
  oauth2:
    client:
      client-id: app_yyc
      client-secret: order123
      access-token-uri: ${sso-server}/oauth/token
      user-authorization-uri: ${sso-server}/oauth/authorize
    resource:
      jwt:
        key-uri: ${sso-server}/oauth/token_key